language: objective-c
before_install:
  - brew update
install:
  - gem install cocoapods
before_script:
  - pod install
script:
  - xctool -workspace Kortkoll.xcworkspace -scheme Kortkoll -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
